language: android
android:
  components:
  - build-tools-28.0.1
  - android-26
  - sys-img-x86-android-26
env:
  global:
    - secure: "O0LvaZY+BjIKRVLtHy7u9C1RAHCA/l9l20sWO7+axM0znXdo0iX0aSGnirHf9cySk4bY+EH4xtSSr+azYbFLlxxb+qy+z52SrJ2EHaY5k6oQP9hnX7/vXjUriV1dVGLAVaJs247NkJ95dLKO+q6zJv3tfegBeKmYSv5XujYbq91e+m2JNu2i4teWUpZpEdQsjONCEQoV3epICvLfjO5zVwvzGkfONcMmG+a4OmG1jahtCoxygWoGj5b0PIT9CBHKkyWgvZXlh/Rr8rbdcBrXEjFFHtBqGRs25T0fkr03ruvFRy/hw0RXzNG66eeHVAoov5Nk1W9HtYtj3mZUt6q7GpkNxyGIQhgYVHMtQtLB0NPYhNqWoTA/qHo9ax9DRLUm71RePL6qyYPw4+jLppN5n9amgQxjwVlcEGOHzTj3CN/UncR0yDcLepbRYQCMBShPwRM+HcsCufZY7RrD2UbHNrmWmKoBedB2LdJ5Q/udJIx5QI5xa8Gcl04jctQMqXDB7XBuY85LrqVOs6Zdy6ijL7/oUee+vIz4ubiLOxoipw0QwTNfTs86yeKFmUtz6n/Jat42ZFVYVwTs4qeCU81TUelMH5b3M4b0+ROYt4TLjzQWczDK7HOeCqY0z074BtK6CLpgT1WR6Yspa+LZSHTntrljHZbswgw1eT/xgzX9bKM="
before_install:
- nvm install 8
install:
- npm install -g cordova
script:
- cordova build android --release
before_deploy:
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore helen-release-key.jks -storepass $storepass platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk helen
  - ${ANDROID_HOME}/build-tools/28.0.1/zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk platforms/android/app/build/outputs/apk/release/helen.apk
deploy:
  provider: releases
  api_key:
    secure: dkHCz6PRN3PNoDuRqQftuRVuFxaKAvulHsEvqYlVpStQ+omUc3J4nnurRdhi3fEHKbwg1XHkXFvRfGUb1qnPfe+ELXaTP+uNLHRtiOLQCFAPnM8YcTwr/cMZGN7s8XNi928v2MRCf3dgJN7hb/0Pr57SV82jHhpFt0D3DmtCakXk0sb+s5dSIOSL9+vTlcWsNFkdtT16wIf6cBlWH5XiL3CYawxtHQSoJQQdNZ3FVQ31qRErQ0LX/rn2wWWxFIQC1JpuZ7L+3Ktg5szo+4SSYBRkCzGdjbv6sIdDPVUM7bKT4ADaF+lFV3dAbt/3P4iNKTcrI7YKx3poGSuqjquO783+zPnN2Ut89Ze7LclQcfNAm+ksSkEmfK+qiZmxqeLWqaLNZRu/lMWJ5oRdDUuxloGiUpcAXRi0xahdA1fkuRtpN55ePCZ1Fx5GGb8CNUOygifK6Tr+ktYy78ROx12FVyNDusXn2WRWGnby5ERXCnIm5V7DEiPlhWxGsi80RoKyiDB4hnPgkAdcqz+LfVNxwDjxhUTMN1Ul49eofN4G1lplIhV3Ss6A7myCBBxttSeeguuv98tZZE6UXppUvXNq9cj93sGdF5guPkOnjrA8xQ73uCYNfU+QHtNHTbAvfSVCrBzEoSKVmduaNaEWTzxVPcHiUi3cpuAy7lDote/3mqM=
  skip_cleanup: true
  file: "platforms/android/app/build/outputs/apk/release/helen.apk"
  on:
    tags: true
    repo: quarkbuddha/helen_in_pocket
