language: android
android:
  components:
  - build-tools-28.0.1
  - android-26
  - sys-img-x86-android-26
before_install:
- nvm install 8
install:
- npm install -g cordova
script:
- cordova build android --release
deploy:
  provider: releases
  api_key:
    secure: PqShtqiypsLyO8xlTQPBer+jM+OL+VHQKsrLzfUi/8ASnh2w9O9kdsO4nHueY/f9YZWo62Cx9nvrtQeboNV1y2lvK6Xyog4RvYnOuQlLzC1z/FdhOPuYRdrLfmvlG5CORworFDfes/VOXXTLcuvxGk0oy70MoTD9OrhNtFFCiuQzaisK1rcWXigb/cbxO9/dffBXik8cpSBNKuuC+NthY6spoKsaAsAbJAqoVWuxzbQFh0oepLknLnlS1+G/MAhhH86xTVwcSjaMay7BN6D65GZbmGdA4iI3KZebf3quI1jwRj7DHItMu92WHF4avRLzQwHZZ1mYUVR1KPaZNHK7LAU/quTc6Tz8XI11PBH2b66iSP9kUTd8uTrS8s9q+Gh0wUKf8ik7P89otJWzHXy1Eoj516RYZ4MmIiUipK32ZoFXHn8IwE/m+bj0+49EqdzT2aDexC+Vp6FR94WQH/EVMamL14os/0HguRu/schm8WoWuN6dL6XB8D5Ctq9eEPeg4Bb9Svve9zFplSTk88qD+wE/pvL14XVshUFfeP/ghiqJD7p7Cmh/UsDveVa068D0W2t/dabLhzKSeRcFMt8HnzvieYUa16Xy+lOG0HWTfqzA65vNK5a2Qk6QGszZVFH/xYA2PMzKd6PsJusdZsAxqvz8mSHS61VdN6hagqsE6Aw=
  file: "$TRAVIS_BUILD_DIR/platforms/android/app/build/outputs/apk/debug/app-release-unsigned.apk"
  on:
    repo: quarkbuddha/helen_in_pocket
