language: android
android:
  components:
    - build-tools-28.0.1
    - android-26
    - sys-img-x86-android-26
before_install:
  - nvm install 8
install:
  - npm install -g cordova
script:
  - cordova build android
